
services:
  postgres:
    image: postgres:15
    container_name: wisdom-postgres
    environment:
      POSTGRES_DB: wisdom
      POSTGRES_USER: wisdom
      POSTGRES_PASSWORD: wisdom123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - wisdom-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wisdom -d wisdom"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: wisdom
      POSTGRES_PASSWORD: wisdom123
      POSTGRES_DB: wisdom
      POSTGRES_SSL_MODE: disable
      ALGORITHM: argon2
      DIFFICULTY: 2
      ADAPTIVE_MODE: true
    networks:
      - wisdom-network
    restart: unless-stopped

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - "8081:8081"
    depends_on:
      - server
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: wisdom
      POSTGRES_PASSWORD: wisdom123
      POSTGRES_DB: wisdom
      POSTGRES_SSL_MODE: disable
      TCP_SERVER_HOST: server
      TCP_SERVER_PORT: 8080
    networks:
      - wisdom-network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:80"
    depends_on:
      - webserver
    networks:
      - wisdom-network

volumes:
  postgres_data:
    driver: local

networks:
  wisdom-network:
    driver: bridge