services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
      - "2112:2112"
    command: ["./server", "-difficulty", "2", "-adaptive", "true"]
    networks:
      - wisdom-net
    # Resource limits for TCP server
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 512M

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - "8081:8081"
    depends_on:
      - server
    command: ["./webserver", "-tcp-server", "server:8080"]
    networks:
      - wisdom-net
    # Recommended resource limits for high-performance simulation
    deploy:
      resources:
        limits:
          cpus: '4.0'     # Increase for extreme simulation (up to 8.0)
          memory: 2G      # Increase for large-scale mining (up to 4G)
        reservations:
          cpus: '2.0'
          memory: 1G

  client1:
    image: world-of-wisdom-client
    depends_on:
      - server
    command: ["-server", "server:8080", "-attempts", "5"]
    networks:
      - wisdom-net

  client2:
    image: world-of-wisdom-client
    depends_on:
      - server
    command: ["-server", "server:8080", "-attempts", "3"]
    networks:
      - wisdom-net

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:80"
    depends_on:
      - webserver
    networks:
      - wisdom-net

networks:
  wisdom-net:
    driver: bridge