services:
  server:
    image: world-of-wisdom-server
    ports:
      - "8080:8080"
      - "2112:2112"
    command: ["./server", "-difficulty", "2", "-adaptive", "true"]
    networks:
      - wisdom-net

  webserver:
    image: world-of-wisdom-webserver
    ports:
      - "8081:8081"
    depends_on:
      - server
    command: ["./webserver", "-tcp-server", "server:8080"]
    networks:
      - wisdom-net

  client1:
    image: world-of-wisdom-client
    depends_on:
      - server
    command: ["-server", "server:8080", "-attempts", "5"]
    networks:
      - wisdom-net

  client2:
    image: world-of-wisdom-client
    depends_on:
      - server
    command: ["-server", "server:8080", "-attempts", "3"]
    networks:
      - wisdom-net

networks:
  wisdom-net:
    driver: bridge