
services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: wisdom-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-wisdom}
      POSTGRES_USER: ${POSTGRES_USER:-wisdom}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wisdom123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - wisdom-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wisdom -d wisdom"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-wisdom}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wisdom123}
      POSTGRES_DB: ${POSTGRES_DB:-wisdom}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE:-disable}
      ALGORITHM: ${ALGORITHM:-argon2}
      DIFFICULTY: ${DIFFICULTY:-2}
      ADAPTIVE_MODE: ${ADAPTIVE_MODE:-true}
    networks:
      - wisdom-network
    restart: unless-stopped

  apiserver:
    build:
      context: .
      dockerfile: Dockerfile.apiserver
    env_file:
      - .env
    ports:
      - "${API_SERVER_PORT:-8081}:8081"
    depends_on:
      - server
      - postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-wisdom}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wisdom123}
      POSTGRES_DB: ${POSTGRES_DB:-wisdom}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE:-disable}
      TCP_SERVER_HOST: ${TCP_SERVER_HOST:-server}
      TCP_SERVER_PORT: ${TCP_SERVER_PORT:-8080}
    networks:
      - wisdom-network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        VITE_API_URL: "http://localhost:8081"
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      - apiserver
    networks:
      - wisdom-network
    environment:
      API_URL: "http://apiserver:8081"

volumes:
  postgres_data:
    driver: local

networks:
  wisdom-network:
    driver: bridge